import smtplib
from socket import gaierror
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from email.utils import COMMASPACE, formatdate
from os.path import basename

def sending_email(email_destination,file):
    port = 588
    smtp_server = "smtp.gmail.com"
    gmail_login = "automaticrosan@gmail.com" # your login generated by Mailtrap
    gmail_password = "rosan2018$$" # your password generated by Mailtrap

    sender = "automaticrosan@gmail.com"
    #receiver = ["jdrs2483@gmail.com","dancero00@gmail.com","jose.daniel.rodriguez.sanchez1@gmail.com"]
    receiver = email_destination

    msg = MIMEMultipart()
    msg['From'] = "automaticrosan@gmail.com"
    #msg['To'] = COMMASPACE.join(send_to)
    msg['To'] = email_destination
    msg['Date'] = formatdate(localtime=True)
    msg['Subject'] = "Este es un correo Automático de Ópticas Rosan - App para crear Cartas."

    # write the HTML part
    html = """<html> 
                    <body> 
                        <p>Hola!
                        <br>
                        <br>
                        Este es un correo automático de <b>Ópticas Rosan</b></p> 
                    </body> 
            </html> """

    msgText = MIMEText(html, "html")
    msg.attach(msgText)

    msg.attach(MIMEText(file))

    #for f in files or []:
    with open(file, "rb") as fil:
        part = MIMEApplication(
            fil.read(),
            Name=basename(file)
        )
    # After the file is closed
    part['Content-Disposition'] = 'attachment; filename="%s"' % basename(file)
    msg.attach(part)


    try:
        smtpserver = smtplib.SMTP(smtp_server, port)
        smtpserver.ehlo()
        smtpserver.starttls()
        smtpserver.ehlo()
        smtpserver.login(gmail_login, gmail_password)
        smtpserver.sendmail(sender, receiver, msg.as_string())
        smtpserver.close()

        print ('Email sent!')
    except (gaierror, ConnectionRefusedError):
        print('Failed to connect to the server. Bad connection settings?')
    except smtplib.SMTPServerDisconnected:
        print('Failed to connect to the server. Wrong user/password?')
    except smtplib.SMTPException as e:
        print('SMTP error occurred: ' + str(e))


#sending_email("jdrs2483@gmail.com","Test.txt")
