import smtplib
from socket import gaierror
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


port = 587 
smtp_server = "smtp.gmail.com"
gmail_login = "dancero00@gmail.com" # your login generated by Mailtrap
gmail_password = "UFO241983" # your password generated by Mailtrap

sender = "automatic_email@test.com"
#receiver = ["jdrs2483@gmail.com","dancero00@gmail.com","jose.daniel.rodriguez.sanchez1@gmail.com"]
receiver = "jdrs2483@gmail.com"

message = MIMEMultipart("alternative")
message["Subject"] = "This is an important message!"
message["From"] = sender
message["To"] = receiver
# Write the plain text part
#text = """Hi, Check out the new post on the Mailtrap blog: SMTP Server for Testing: Cloud-based or Local? https://blog.mailtrap.io/2018/09/27/cloud-or-local-smtp-server/ Feel free to let us know what content would be useful for you!"""

# write the HTML part
html = """<html> 
                <body> 
                    <p>Hello!<br><br> Please take a look into the following link:</p> 
                    <p>
                        <a href="https://google.com">Search Info...</a>
                    </p> 
                </body> 
        </html> """

# convert both parts to MIMEText objects and add them to the MIMEMultipart message
#part1 = MIMEText(text, "plain")
part2 = MIMEText(html, "html")


#message.attach(part1)
message.attach(part2)


try:
    server = smtplib.SMTP('smtp.gmail.com', port)
    server.ehlo()
    server.starttls()
    server.login(gmail_login, gmail_password)
    server.sendmail(sender, receiver, message.as_string())
    server.close()

    print ('Email sent!')
except (gaierror, ConnectionRefusedError):
    print('Failed to connect to the server. Bad connection settings?')
except smtplib.SMTPServerDisconnected:
    print('Failed to connect to the server. Wrong user/password?')
except smtplib.SMTPException as e:
    print('SMTP error occurred: ' + str(e))
